### ISSUE TITLE
PR title does not always include the commit message

### ISSUE THREAD

**Issue by vesapupovci** [gorillio/github-action-cherry-pick#9]
Hi,

I have added a workflow that uses this action and creates two PRs (one on `develop` branch and one on `qa` branch) when pushing to `uat` branch:

```

name: Hotfix in UAT
on:
  push:
    branches:
      - "uat"
jobs:
  release_pull_request:
    runs-on: ubuntu-latest
    name: release_pull_request
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Create PR to branch QA
      uses: gorillio/github-action-cherry-pick@master
      with:
        pr_branch: 'qa'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITBOT_EMAIL: <BOT_EMAIL>
        DRY_RUN: false
    - name: Create PR to branch develop
      uses: gorillio/github-action-cherry-pick@master
      with:
        pr_branch: 'develop'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITBOT_EMAIL: <BOT_EMAIL>
        DRY_RUN: false
```

Everything works fine, two PRs are created but the title of one of the PRs (the first one that gets created) is just `AUTO:` and does not include the commit message. Please see screenshot. 

Am I doing something wrong?

![Screen Shot 2022-09-09 at 11 48 18 AM](https://user-images.githubusercontent.com/55283591/189323240-0b4bcb3f-c1b6-4bd6-b2ab-d37158468484.png)
![Screen Shot 2022-09-09 at 11 48 27 AM](https://user-images.githubusercontent.com/55283591/189323243-07fb09a9-62c9-4903-8a8b-0162ea6b99d6.png)
